### ISSUE TITLE
Brainstorm para indicações de ideias em projetos de software

### ISSUE THREAD

**Issue by radamesp7** [radamesp7/AbexII_G2_2024#1]
O brainstorming se aplica a disciplina de aprendizado baseado em experiências, onde os alunos em grupos indicam o que pode ser uma ideia de problema que possa ser solucionado com o desenvolvimento de um aplicativo de software e que tem uma finalidade prática. O brainstoriming deve gerar ideias entre os membros do grupo e precisa que se use como base o github para que possam trabalhar como grupo de trabalho e registrar as ideias conforme forem gerando as mesmas.

 Lista de Ideias:

**Comment by InayeMachado** [comment]
Aplicativo de lista de tarefas

**Comment by InayeMachado** [comment]
Aplicativo de registro de livros para bibliotecas de escolas.

**Comment by Dudu-uno** [comment]
App de controle de giro de estoque
